### ISSUE TITLE
Hashing password

### ISSUE THREAD

**Issue by hiddehoi** [raketwissenschaftler/somtoday_api#1]
De hash voor het wachtwoord klopt niet. Je kunt dit wel doen via onder andere
$wachtwoord = '';
$hash = base64_encode(sha1($wachtwoord, true));
$hex = bin2hex($hash);
echo $hex;

**Comment by matgeroe** [comment]
what he said

**Comment by matgeroe** [comment]
wijzig de functie als volgt: 

``` php
private function hashAndEncodePassword($password) {
        // Yes, SOMtoday is using SHA1. This is a shame!
        $hash = sha1($password,true);
        // Base64, how useless..
        $hash = base64_encode($hash);
        // Converting string to hex, another useless layer
        $hash = bin2hex($hash);
        return $hash;

    }
```

creds @hiddehoi

**Comment by raketwissenschaftler** [comment]
Sorry, door een fout in mijn mailfilter heb ik hier niks van meegekregen. Matgeroe, als je even een pull request stuurt zal ik deze fix mergen.
