### ISSUE TITLE
Scholen die niet in servers.somtoday.nl voorkomen

### ISSUE THREAD

**Issue by tschoffelen** [raketwissenschaftler/somtoday_api#14]
Ik kwam er gisteren achter dat er een aantal scholen zijn die niet voorkomen in de lijst servers.somtoday.nl, maar wel toegang hebben tot SOMtoday. Voorbeeld hiervan is:

> Gooise Scholen Federatie: https://somtoday.nl/gsf

Dit heeft er waarschijnlijk mee te maken dat SOMtoday over is gegaan van hun mobiele app op alleen nog maar de responsive website, en de lijst op servers.somtoday.nl blijkbaar niet meer geupdated wordt. Iemand een oplossing hiervoor?

**Comment by raketwissenschaftler** [comment]
Dit is simpel genoeg, namelijk bij de lijst van https://servers.somtoday.nl/ zelf deze toevoegen. Dit is misschien niet te doen voor iedere school, maar als je je eigen mist wel. Voor de rest kun je je eigen lijst eventueel bouwen door middel van deze link: https://somtoday.nl/domein?-IResourceListener-content-organisatieSelectionForm-organisatieSearchFieldPanel-organisatieSearchFieldPanel_body-organisatieSearchField&term=, en dan bij term alle letters van a-z invullen, want dan krijg je alle scholen die somtoday gebruiken. 

Ik ga misschien binnenkort nog even aan de slag met het parsen van hun website, maar daar heb ik nu nog even geen zin in tbh :P
