### ISSUE TITLE
API has changed

### ISSUE THREAD

**Issue by thomasbeukema** [raketwissenschaftler/somtoday_api#16]
The somtoday API has changed, so this doesn't work anymore

**Comment by raketwissenschaftler** [comment]
Tja, ik ben zelf (gelukkig) al lang van SomToday af. (Klein detail: er zijn nog ergere grafsystemen, namelijk OASE). Ik hoop dat mijn werk mensen geholpen heeft, maar ik kan er zelf eigenlijk vrij weinig aan doen. De app die ik als bron gebruikt heb voor mijn huidige code, de SomToday Android app, heeft ook een update meer gehad sinds januari 2015, dus eventuele veranderingen kan ik niet meer daar uithalen. De website van SomToday werkt verder niet asynchroon, dus dan zou je daar een parser op los moeten laten, in de plaats van hoe het nu gaat. 

Kortom: Als iemand dit op wil pakken en hulp o.i.d. nodig heeft wil ik zeker kijken wat ik kan doen, maar het zelf bouwen van een nieuwe versie gaat 'm niet meer worden :/
