### ISSUE TITLE
Where can i set my Username/Password/Schoolname/Brin

### ISSUE THREAD

**Issue by TheIndra55** [raketwissenschaftler/somtoday_api#3]
Hello, Thanks for your api!

But Where can i see the SchoolName/Username/Password/Brin

Thanks!

<b>EDIT:</b> I use the PHP File!

**Comment by raketwissenschaftler** [comment]
To set it, just initialize a new SomtodayUser class with your username and password and stuff. I am not sure what you mean to be honest, because of the conflicting title

**Comment by RickBakkr** [comment]
I guess this issue can be closed?
