### ISSUE TITLE
How do I make this interact with a c# application

### ISSUE THREAD

**Issue by christosk92** [raketwissenschaftler/somtoday_api#4]
Hey,
Thanks for your api. I have a question,  I am creating a app for my school and I just need some help. How do I make this php file interact with my c# application. I am using the windows 10 sdk.

Thanks,
C

**Comment by raketwissenschaftler** [comment]
First: https://www.microsoft.com/en-us/store/apps/somtomorrow/9nblggh3g29f.
There is a win10 version coming pretty soon. I am planning on making that one ad-free and open source, so if you want to collaborate, keep an eye on my github.

Second: I am not going to write a ready-made snippet for you, but look at the json somtoday sends you, http://pastebin.com/gB7tF9ZW and use https://msdn.microsoft.com/en-US/library/windows/apps/windows.web.http.httpclient and http://www.newtonsoft.com/json. If you have any additional questions, please ask them.

**Comment by christosk92** [comment]
Hallo,
Ik heb misschien gemerkt dat je NL bent van  je app.
Ik begrijp dat je geen klaargemaakte snippets kan geven alleen ik heb probleempjes met het ophalen van de JSON Code. Ik krijg:  {"leerlingen":null,"verzorger":false,"error":"FAILED_AUTHENTICATION"}

Als ik naar de somtoday pagina van mijn school ga staat er: merewa-elo.somtoday.com dus vul ik bij schoolname: merewa in. Ik heb het wachtwoord gehashed. 
Verder weet ik nu wel hoe ik de json moet deserializen in C# met JSON.NET(Heb er al vaker mee gewerkt)

**Comment by christosk92** [comment]
Mijn excuses: merewa-elo.somtoday.nl/ *

**Comment by raketwissenschaftler** [comment]
Oke, welke code heb je al gebruikt? Dan kan ik zien waar het fout gaat.

**Comment by christosk92** [comment]
ik heb de code van de login functie snel gepakt en geplakt in een andere php bestand, samen met de hash functie:
<?php

$username = "----NAAM---";
$password ="---WACHTWOORD---";
$BRIN = "24TP";
$schoolName = "merewa";
function hashAndEncodePassword($password) {
        // Yes, SOMtoday is using SHA1. This is a shame!
        $hash = sha1($password,true);
        // Base64, how useless..
        $hash = base64_encode($hash);
        // Converting string to hex, another useless layer
        $hash = bin2hex($hash);
        return $hash;

```
}
```

$passwordHash = hashAndEncodePassword( $password );

```
    $baseURL = "https://somtoday.nl/" . $schoolName . "/services/mobile/v10/";

    $url = $baseURL . "Login/CheckMultiLoginB64/" . $username . "/" . $passwordHash. "/" . $BRIN;

    $response = json_decode(file_get_contents( $url ));
```

   echo file_get_contents($url);
        ?>

**Comment by raketwissenschaftler** [comment]
Maar zit de c#, zit die clientside of serverside? Want anders snap ik niet wat je met php wil doen en zou ik gewoon mijn eigen JSON deserializen en verder verwerken

**Comment by christosk92** [comment]
Misschien heb je mij verkeerd geinterpreteerd. Ik zou dat gebruikers van mijn school kunnen inloggen met hun gebruikersnaam en wachtwoord en hun rooster etc kunnen bekijken. 
De json word weergeven door die echo en mijn c# code gaat dus naar dat php bestand en leest die php code. In c# deserialized mijn code de json zodat hij kan worden ingevoegd in listviews etc( CIjferlijsten)

**Comment by christosk92** [comment]
wacht dit is wat ik wil. Even kort samengevat:

PHP returnt een JSON. Die json komt van die SOMToday.
C# Code leest json en deserialized
Deserialized JSON Word in listview geplaatst

**Comment by christosk92** [comment]
En c# zit op clientside

**Comment by raketwissenschaftler** [comment]
En waarom zou je dan nog een extra stap doen via php, en niet direct in je clientside code met een HttpClient de api aanroepen?

**Comment by christosk92** [comment]
Omdat ik eerlijk gezegd niet weet hoe dat moet. Welke url moet ik oproepen?

**Comment by raketwissenschaftler** [comment]
Oke, in somtoday.py staat bij iedere functie een url, zoals 

> gradesurl = self.baseurl + "Cijfers/GetMultiCijfersRecentB64/" + self.username + "/" + self.password + "/" +  self.brin + "/" + self.leerlingId

De baseurl ziet er zo: baseurl = "https://somtoday.nl/" + schoolname + "/services/mobile/v10/" uit. Dit is opzich geen raketwetenschap (snap je hem? raketwissenschaftler? grappig he???). Schoolname komt uit http://servers.somtoday.nl.

De username is de standaard username, base64 encoded. Password is het wachtwoord door de rare hashfunctie van somtoday heengehaald en brin is vrij duidelijk. In c# ziet dit er zo uit:
    var sha1 = WinRTCrypto.HashAlgorithmProvider.OpenAlgorithm(HashAlgorithm.Sha1);
    byte[] passwordArray = Encoding.UTF8.GetBytes(password);
    byte[] hash = sha1.HashData(passwordArray);
    string hashedAndBase64 = Convert.ToBase64String(hash);
    string output = ToHex(hashedAndBase64);
    password = output;

Voor ToHex kan je deze functie gebruiken, maar kudos als je iets netters kan maken.
        private string ToHex(string inputstring)
        {
            string output = "";
            string hexChars = "0123456789abcdef";
            foreach (char hexChar in inputstring)
            {
                int asciiValue = (int)hexChar;
                int index1 = asciiValue % 16;
                int index2 = (asciiValue - index1) / 16;
                output += hexChars[index2];
                output += hexChars[index1];
            }
            return output;
        }

De base64 functie moet je zelf even maken, maar dat is ook niet al te moeilijk.

Het leerlingid dat ik gebruik komt uit de login url, maar die kan je in somtoday.py vinden.

**Comment by christosk92** [comment]
Heel erg bedankt.
Ik ga nu even alles opzoeken!
En trouwens, erg bedankt voor die somtoday app! Ben er echt blij mee. Die stomme tropicus was waarschijnlijk te gierig ofzo haha. Maak van de uwp app iets mooi!
