### ISSUE TITLE
{"leerlingen":null,"verzorger":false,"error":"FAILED_AUTHENTICATION"}

### ISSUE THREAD

**Issue by FeedyFeedback** [raketwissenschaftler/somtoday_api#5]
Hoi, waarom werkt dit neit? (Login naam en pass heb ik nert getest op officiële site en werkt gewoon)

Error: {"leerlingen":null,"verzorger":false,"error":"FAILED_AUTHENTICATION"}

<?php
$username = "++username"++";
$password ="++Password++";
$BRIN = "19HG";
$schoolName = "twickel";
function hashAndEncodePassword($password) {
// Yes, SOMtoday is using SHA1. This is a shame!
$hash = sha1($password,true);
// Base64, how useless..
$hash = base64_encode($hash);
// Converting string to hex, another useless layer
$hash = bin2hex($hash);
return $hash;

} 

$passwordHash = hashAndEncodePassword( $password );

$baseURL = "https://somtoday.nl/" . $schoolName . "/services/mobile/v10/"; $url = $baseURL . "Login/CheckMultiLoginB64/" . $username . "/" . $passwordHash. "/" . $BRIN; $response = json_decode(file_get_contents( $url )); 

echo file_get_contents($url);
?>

**Comment by raketwissenschaftler** [comment]
Hey Niels,
Welke code gebruik je om de API aan te roepen?

**Comment by FeedyFeedback** [comment]
Hoi, ik bedenk me dat nu ineens ook. Ik zag in een andere issue dat dit gebruikt werd, dus ik dacht dat dat wel zou werken

**Comment by raketwissenschaftler** [comment]
Is het opgelost? anders zou het fijn zijn als je even de code die je gebruikt in je programma gebruikt kan posten, dan kan ik zien wat je fout doet.

**Comment by FeedyFeedback** [comment]
Dat wat ik heb gepost is de enige code die ik heb gebruikt. Het stond in een andere post, en er stond niet "include "somtoday.php"" dus ik dacht dat die code in die post alleen al zou werken. (Die issue die ik bedoel is de andere issue op deze repository)

**Comment by raketwissenschaftler** [comment]
Oke, om deze api te gebruiken include je somtoday.php en dan moet je iets als dit gebruiken:
(alvast mijn excuses, ik heb al 2 jaar geen php meer geschreven)

$som = new SOMtodayUser($username, $password, $schoolname, $brin);

en dan kan je hiermee dingen aanroepen, zoals om je cijfers te krijgen:

$grades = $som->getGrades();

**Comment by FeedyFeedback** [comment]
Werkt nog steeds niet :(

<?php
include "somtoday.php";
$username = "--Leerlingnummer--";
$password ="--Password---";
$BRIN = "19HG";
$schoolName = "twickel";
//function hashAndEncodePassword($password) {
//// Yes, SOMtoday is using SHA1. This is a shame!
//$hash = sha1($password,true);
//// Base64, how useless..
//$hash = base64_encode($hash);
//// Converting string to hex, another useless layer
//$hash = bin2hex($hash);
//return $hash;
//
//} 
//
//$passwordHash = hashAndEncodePassword( $password );
//
//$baseURL = "https://somtoday.nl/" . $schoolName . "/services/mobile/v10/"; $url = $baseURL . "Login/CheckMultiLoginB64/" . $username . "/" . $passwordHash. "/" . $BRIN; $response = json_decode(file_get_contents( $url )); 
//
//echo file_get_contents($url);
$som = new SOMtodayUser($username, $password, $schoolname, $BRIN);
$grades = $som->getGrades();
echo $grades;
?>

**Comment by raketwissenschaftler** [comment]
Staat het bestand somtoday.php wel in dezelfde dir als het bestand waar je het gebruikt? En welke error krijg je?

**Comment by FeedyFeedback** [comment]
Het staat in dezelfde dir.

[Sun Dec 20 12:20:04 2015] [warn] [client IP] mod_fcgid: stderr: PHP Notice:  Undefined variable: login_url in /var/www/clients/client684/web1298/web/somtoday.php on line 77
[Sun Dec 20 12:20:04 2015] [warn] [client IP] mod_fcgid: stderr: PHP Warning:  file_get_contents(): Filename cannot be empty in /var/www/clients/client684/web1298/web/somtoday.php on line 77
[Sun Dec 20 12:20:04 2015] [warn] [client IP] mod_fcgid: stderr: PHP Warning:  file_get_contents(Cijfers/GetMultiCijfersRecentB64/307990//19HG/): failed to open stream: No such file or directory in /var/www/clients/client684/web1298/web/somtoday.php on line 132

**Comment by raketwissenschaftler** [comment]
Wanneer heb je somtoday.php gedownload? Is dit toevallig een tijdje geleden, want ik zie dat je password niet geëncode wordt, en in een oude versie zat een bug waar dit niet lukte.

**Comment by FeedyFeedback** [comment]
half uur geleden gedownload

**Comment by raketwissenschaftler** [comment]
Oke, kan je dan bij zowel de functie login als getgrades toevoegen: echo $url, zodat ik kan zien hoe de url eruit ziet
Mocht je dit liever niet via deze issue doen, mail me dan even via raketwissenschaftler op outlook.com

**Comment by FeedyFeedback** [comment]
https://somtoday.nl/twickel/services/mobile/v10/Login/CheckMultiLoginB64/307990/BIJDEZESTAAT WEL HET WACHTWOORD/19HG

Cijfers/GetMultiCijfersRecentB64/307990//19HG/

De eerste echo is function login, de 2e is grades

**Comment by FeedyFeedback** [comment]
Als je die bovenstaande link invoert in je browser komt alsnog dit: {"leerlingen":null,"verzorger":false,"error":"FAILED_AUTHENTICATION"}

**Comment by raketwissenschaftler** [comment]
oke, kan je kijken of het werkt met het python script?

**Comment by FeedyFeedback** [comment]
is goed ga ik proberen

**Comment by FeedyFeedback** [comment]
Ik heb nog nooit gewerkt met python, en ik krijg error : Syntaxerror: invalid syntax... Ik typ python setup.py install

**Comment by raketwissenschaftler** [comment]
Oke, wacht, ik denk dat ik het weet

vervang in de constructor dit: $this->username = $username;
door $this->username = bin2hex(base64_encode($username));

En setup.py werkt niet idd, je moet gewoon import somtoday_api doen

**Comment by FeedyFeedback** [comment]
Nope werkt niet

**Comment by raketwissenschaftler** [comment]
Welke error krijg je nu dan?

**Comment by FeedyFeedback** [comment]
Nouja hij encode mijn gebruikersnaam wel, maar bij grades is er nog steeds geen ww:
{"leerlingen":null,"verzorger":false,"error":"FAILED_AUTHENTICATION"}
https://somtoday.nl/twickel/services/mobile/v10/Login/CheckMultiLoginB64/307990/MIJNWW/19HG

Cijfers/GetMultiCijfersRecentB64/4d7a41334f546b77//19HG/

**Comment by FeedyFeedback** [comment]
dit is mijn momentele php script:

<?php
include "somtoday.php";
$username = "307990";
$password ="MIJNWW";
$BRIN = "19HG";
$schoolName = "twickel";
function hashAndEncodePassword($password) {
// Yes, SOMtoday is using SHA1. This is a shame!
$hash = sha1($password,true);
// Base64, how useless..
$hash = base64_encode($hash);
// Converting string to hex, another useless layer
$hash = bin2hex($hash);
return $hash;

} 

$passwordHash = hashAndEncodePassword( $password );

$baseURL = "https://somtoday.nl/" . $schoolName . "/services/mobile/v10/"; 
$url = $baseURL . "Login/CheckMultiLoginB64/" . $username . "/" . $passwordHash. "/" . $BRIN; $response = json_decode(file_get_contents( $url )); 

echo file_get_contents($url);
$som = new SOMtodayUser($username, $passwordHash, $schoolName, $BRIN);
$grades = $som->getGrades();
echo $grades;
?>

**Comment by raketwissenschaftler** [comment]
Ah, nu zie ik waar het fout gaat. Je hasht het password al zelf, en dat moet je niet doen. Zo moet het eruit zien:
<?php
include "somtoday.php";
$username = "307990";
$password ="MIJNWW";
$BRIN = "19HG";
$schoolName = "twickel";

$som = new SOMtodayUser($username, $passwordHash, $schoolName, $BRIN);
$grades = $som->getGrades();
echo $grades;
?>

**Comment by FeedyFeedback** [comment]
https://somtoday.nl/twickel/services/mobile/v10/Login/CheckMultiLoginB64/307990//19HG

Cijfers/GetMultiCijfersRecentB64/4d7a41334f546b77//19HG/

Dit krijg ik dan

Dit is nu het script:

<?php
include "somtoday.php";
$username = "307990";
$password ="WW";
$BRIN = "19HG";
$schoolName = "twickel";
$som = new SOMtodayUser($username, $passwordHash, $schoolName, $BRIN);
$grades = $som->getGrades();
echo $grades;
?>

**Comment by niels515** [comment]
hij doet het wachtwoord dus niet

**Comment by niels515** [comment]
maar als ik daarvoor een speciaal php scriptje maak om te testen of hij wel een password omzet, dan werkt het wel. Gebruik ik dan het omgezette username en password, zegt die nog steeds geen authenticatie

(ik heb dus de omgezette username in de url gedaan, en t password verkregen via dit:)

<?php
$password = "MIJNWW";
function hashAndEncodePassword($password) {
// Yes, SOMtoday is using SHA1. This is a shame!
$hash = sha1($password,true);
// Base64, how useless..
$hash = base64_encode($hash);
// Converting string to hex, another useless layer
$hash = bin2hex($hash);
return $hash;
} 

$passwordHash = hashAndEncodePassword( $password );

echo $passwordHash;
?>

**Comment by niels515** [comment]
[Sun Dec 20 13:06:08 2015] [warn] [client 163.158.172.238] mod_fcgid: stderr: PHP Notice:  Undefined variable: passwordHash in /var/www/clients/client684/web1298/web/niels.php on line 7
[Sun Dec 20 13:06:08 2015] [warn] [client 163.158.172.238] mod_fcgid: stderr: PHP Notice:  Undefined variable: login_url in /var/www/clients/client684/web1298/web/somtoday.php on line 76
[Sun Dec 20 13:06:08 2015] [warn] [client 163.158.172.238] mod_fcgid: stderr: PHP Warning:  file_get_contents(): Filename cannot be empty in /var/www/clients/client684/web1298/web/somtoday.php on line 76
[Sun Dec 20 13:06:08 2015] [warn] [client 163.158.172.238] mod_fcgid: stderr: PHP Warning:  file_get_contents(Cijfers/GetMultiCijfersRecentB64/4d7a41334f546b77//19HG/): failed to open stream: No such file or directory in /var/www/clients/client684/web1298/web/somtoday.php on line 131

ERROR LOG

**Comment by niels515** [comment]
Als ik de function weer in mijn php script zet "hasht" hij het password wel weer

**Comment by FeedyFeedback** [comment]
mod_fcgid: stderr: PHP Notice:  Undefined variable: login_url in /var/www/clients/client684/web1298/web/somtoday/somtoday.php on line 77

hier komt het miss door?

**Comment by raketwissenschaftler** [comment]
Goed gezien. Probeer eens op regel 77 
$response = json_decode( file_get_contents( $login_url ) );
te vervangen door:
$response = json_decode( file_get_contents( $lurl ) );

**Comment by FeedyFeedback** [comment]
lurl of url? want bij lurl geeft hij undefined variable en bij url geefft hij deze error: 

[Sun Dec 20 13:31:27 2015] [warn] [client 163.158.172.238] mod_fcgid: stderr: PHP Fatal error:  Cannot use object of type stdClass as array in /var/www/clients/client684/web1298/web/somtoday/somtoday.php on line 79

[Sun Dec 20 13:31:28 2015] [warn] [client 163.158.172.238] mod_fcgid: stderr: PHP Fatal error:  Cannot use object of type stdClass as array in /var/www/clients/client684/web1298/web/somtoday/somtoday.php on line 79

**Comment by raketwissenschaftler** [comment]
url inderdaad

**Comment by FeedyFeedback** [comment]
ja dan krijg ik de bovnenstaande error

**Comment by raketwissenschaftler** [comment]
Begin eens met debuggen wat er op regel 79 gebeurt, ik verwacht wel een beetje eigen input.

**Comment by FeedyFeedback** [comment]
Sorry, heb niet zo veel verstand van PHP, ik heb het al naar mn maatje gestuurd. Ik wacht nu op zijn reactie

**Comment by raketwissenschaftler** [comment]
Ik ben zelf ook al een tijdje uit php, en ik heb zo snel even geen php omgeving klaar, dus ik kan niet testen. Als jullie het opgelost krijgen, stuur dan een pull request als je wil.

**Comment by FeedyFeedback** [comment]
Is goed

**Comment by ApocalypsjeNL** [comment]
als je regel 79 debugt komt er dit uit: stdClass Object ( [leerlingen] => [verzorger] => [error] => FAILED_AUTHENTICATION )

**Comment by raketwissenschaftler** [comment]
Ik ben xampp aan het downloaden, dus ik zal er even naar kijken, maar ik heb de php-versie niet geschreven, dus ik weet er vrij weinig van af.

**Comment by ApocalypsjeNL** [comment]
Als ik het met me eigen gegevens doet geeft hij een internal server error aan op de somtoday site.

**Comment by niels515** [comment]
das niet zo handig

**Comment by FeedyFeedback** [comment]
ik zal wel ff contact maken met die php developer. Deze gast toch? https://github.com/matgeroe

**Comment by ApocalypsjeNL** [comment]
![schermopname 18](https://cloud.githubusercontent.com/assets/10475082/11918130/fbcc73b6-a724-11e5-8088-f229a5cfd771.png)
als ik het met me eigen gegevens doe geeft hij deze error

**Comment by RickBakkr** [comment]
Ik ben momenteel ook bezig hiermee. Het PHP script is echt heel raar. Ben nu zelf bezig met een nieuwe PHP wrapper. Als het lukt pull ik deze vanmiddag :)

**Comment by FeedyFeedback** [comment]
@RickBakkr ooke dat zou fijn zijn :)

**Comment by FeedyFeedback** [comment]
@apocalypsjenl als je nou eens je username hasht?

**Comment by RickBakkr** [comment]
Yay! Ik heb de authenticatie nu wel goed! 
Zal het ff pullen.

**Comment by FeedyFeedback** [comment]
@RickBakkr oke heel erg bedankt :)

**Comment by ApocalypsjeNL** [comment]
@niels515 hij heeft zelfde error met een gehasht password

**Comment by RickBakkr** [comment]
Als jullie nog 10 min wachten, ga ik hard aan de slag!

**Comment by FeedyFeedback** [comment]
@apocalypsjeNL k bedoel username :P 
@RickBakkr is goed :)

**Comment by ApocalypsjeNL** [comment]
Dan geeft hij zelfde fout als jij hebt inderdaad

**Comment by RickBakkr** [comment]
Gepulled! https://github.com/RickBakkr/somtoday_api/blob/a4b8a74a2d8ecec1d7eb0efce071d9170e066cdb/somtoday.php

Totdat @raketwissenschaftler het accepteert staat het hier!

**Comment by FeedyFeedback** [comment]
@RickBakkr bedankt ik ga er nu naar kijken :) 
@ApocalypsjeNL jup

**Comment by RickBakkr** [comment]
Let wel, het loopt nog ergens stuk!!
De authenticatie method werkt echter wel :)

**Comment by ApocalypsjeNL** [comment]
als ik mijn gegevens invoer krijg ik nogsteeds dit: stdClass Object ( [leerlingen] => [verzorger] => [error] => FAILED_AUTHENTICATION )

**Comment by RickBakkr** [comment]
Ook met mijne?

**Comment by raketwissenschaftler** [comment]
@RickBakkr ik heb even een pull request nodig, dan kan hij door naar de master.

**Comment by ApocalypsjeNL** [comment]
@RickBakkr Ja

**Comment by RickBakkr** [comment]
Bingo!!!

Gefixt! Zal nu pull request doen.

**Comment by ApocalypsjeNL** [comment]
nu geeft hij 500 error

**Comment by ApocalypsjeNL** [comment]
met oude code van @RickBakkr

**Comment by RickBakkr** [comment]
@ApocalypsjeNL dat weet ik. Komt dordat iets verkeerd wordt aangeroepen. Fix wordt nu gepulled!

**Comment by RickBakkr** [comment]
https://github.com/raketwissenschaftler/somtoday_api/pull/6

Accept aub!

**Comment by RickBakkr** [comment]
Deze code is echt bagger. Moment. Moet nog het een en ander doen voordat het ook goed werkt. Bloody shame, de auteur....

**Comment by RickBakkr** [comment]
De pull request komt er zo aan :)

**Comment by FeedyFeedback** [comment]
:)

**Comment by RickBakkr** [comment]
https://github.com/raketwissenschaftler/somtoday_api/pull/7

Please accept!

**Comment by RickBakkr** [comment]
Demo:
http://rickbakker.eu/som/test.php

**Comment by RickBakkr** [comment]
Even iets anders: je kunt een array niet echo'en.
Dus echo $som->getGrades(); kan niet ;)

**Comment by FeedyFeedback** [comment]
niceeeeeeeee

**Comment by RickBakkr** [comment]
Your welcome!

**Comment by raketwissenschaftler** [comment]
Oke, goed gedaan @RickBakkr . Het echo'en van de array wist ik niet, omdat het laatste wat ik met php deed 2 jaar geleden was. Als je wilt mag je readme.md ook aanpassen en je eigen naam er neerduwen

**Comment by FeedyFeedback** [comment]
kan je miss de source delen? (pass en naam hoef je natuurlijk er niet inte zetten )

**Comment by FeedyFeedback** [comment]
plzzz

**Comment by RickBakkr** [comment]
Bedankt @raketwissenschaftler.

Ieder z'n vak hè, waar ik erg actief bezig ben op PHP gebied, zul jij dat wel meer zijn in Python.

@niels515 Het is open source? :')

**Comment by FeedyFeedback** [comment]
@RickBakkr nee k bedoel die test.php

**Comment by FeedyFeedback** [comment]
@RickBakkr want dit werkt niet: 

<?php
include "somtoday.php";
$username = "307990";
$password ="MIJN WW";
$BRIN = "19HG";
$schoolName = "twickel";

$som = new SOMtodayUser($username, $passwordHash, $schoolName, $BRIN);
$grades = $som->getGrades();
echo $grades;
?>

**Comment by RickBakkr** [comment]
@niels515 

Wat zei ik nou net? Je kunt een array niet echo'en.
Dus echo $som->getGrades(); kan niet ;)

**Comment by RickBakkr** [comment]
var_dump() of print_r() kun je echter wel gebruiken om een array gewoon zo weer te geven. Dit is echter alleen voor debugging.

Je kunt bv. een foreach loop gebruiken om elke row terug te geven.

(FYI: in de demo gebruikte ik var_dump)

**Comment by FeedyFeedback** [comment]
jup maar dan krijg ik 500 error...

**Comment by FeedyFeedback** [comment]
lol nu werkt t vgm
SOMtodayUser Object ( [pupilID] => 199788347 [fullname] => [username] => MzA3OTkw [password:SOMtodayUser:private] => MIJNWW[schoolName] => twickel [BRIN] => 19HG [baseURL] => https://somtoday.nl/twickel/services/mobile/v10/ [fullName] => Niels Achternaam)

**Comment by niels515** [comment]
maar dat zijn geen grades... :P

**Comment by FeedyFeedback** [comment]
Het is gelukt. Heel erg bedankt voor je hulp  en je pull request :)

**Comment by RickBakkr** [comment]
Mocht er iets niet lukken, mail me gerust. Als je graag via Skype support wilt, kan je ook een mailtje sturen. :+1: 

Het lijkt me niet handig om hier te blijven praten over jouw specifieke kwestie.

**Comment by raketwissenschaftler** [comment]
@niels515 @RickBakkr Jep, ik ga hem closen.
